# Generated by Django 5.1.7 on 2025-03-19 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of Movie:', max_length=50)),
                ('date', models.DateField()),
                ('genre', models.CharField(help_text='Genre of Movie:', max_length=50)),
                ('dic', models.CharField(help_text='Name of Movie Director:', max_length=50)),
                ('rate', models.IntegerField()),
            ],
        ),
    ]
