# Generated by Django 5.1.7 on 2025-04-13 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_movie_rate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='dic',
            new_name='director',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='rate',
            new_name='rating',
        ),
    ]
